### Contexto del Dataset

Este conjunto de datos consolida estadísticas educativas de Colombia a nivel territorial. Su estructura abarca:
* **Alcance temporal:** 14 años de registros consolidados (`AÑO`).
* **Alcance geográfico:** 34 categorías territoriales (`DEPARTAMENTO`), incluyendo los departamentos del país y Bogotá D.C.
* **Métricas principales:** * **Demografía y Acceso:** Población objetivo escolar, tasas de matriculación y coberturas (neta y bruta).
    * **Infraestructura escolar:** Tamaño promedio de grupo y porcentaje de sedes conectadas a internet.
    * **Trayectoria y Desempeño:** Tasas de deserción, aprobación, reprobación y repitencia. Todas estas métricas están desglosadas por nivel educativo (Transición, Primaria, Secundaria y Educación Media).

###  Limpieza y Transformación del Dataset

Para preparar los datos antes del análisis de deserción escolar, se le aplicó el siguiente tratamiento al dataset:

* **Exploración inicial:** Revisamos la estructura general, tipos de datos, valores únicos por columna y confirmamos que no hay filas duplicadas.
* **Transformación de porcentajes (0 a 1):** Más de 30 columnas (como coberturas, tasas de deserción, aprobación, etc.) venían como texto (`object`) con el símbolo `%` y comas. Se limpiaron estos caracteres y se convirtieron a tipo `float` en una escala decimal de 0 a 1.
* **Ajuste de variables específicas:** * `TAMAÑO_PROMEDIO_DE_GRUPO`: Se pasó a numérico cambiando la coma por punto.
    * `SEDES_CONECTADAS_A_INTERNET`: Se dividió entre 100 para unificarla a la misma escala decimal (0 a 1) del resto de las tasas.
* **Exportación para Excel:** Guardamos el resultado final en `datos_educacion_limpios.csv` utilizando codificación `utf-8-sig`, separador de punto y coma (`;`) y decimales con coma (`,`) para garantizar que Excel lea perfectamente las tildes, las eñes y los números.

In [18]:
import pandas as pd

In [19]:
path = "/content/MEN_ESTADISTICAS_EN_EDUCACION_EN_PREESCOLAR,_BÁSICA_Y_MEDIA_POR_DEPARTAMENTO_20260301.csv"
data = pd.read_csv(path)

In [20]:
data.head()

,AÑO,CÓDIGO_DEPARTAMENTO,DEPARTAMENTO,POBLACIÓN_5_16,TASA_MATRICULACIÓN_5_16,COBERTURA_NETA,COBERTURA_NETA_TRANSICIÓN,COBERTURA_NETA_PRIMARIA,COBERTURA_NETA_SECUNDARIA,COBERTURA_NETA_MEDIA,...,REPROBACIÓN,REPROBACIÓN_TRANSICIÓN,REPROBACIÓN_PRIMARIA,REPROBACIÓN_SECUNDARIA,REPROBACIÓN_MEDIA,REPITENCIA,REPITENCIA_TRANSICIÓN,REPITENCIA_PRIMARIA,REPITENCIA_SECUNDARIA,REPITENCIA_MEDIA
0,2011,5,Antioquia,1288473,"94,01%","93,85%","70,28%","94,12%","75,68%","44,37%",...,"2,06%","0,07%","94,56%","2,54%","2,96%","4,25%","0,07%","4,56%","5,27%","1,68%"
1,2011,8,Atlántico,523935,"99,32%","99,05%","50,59%","98,93%","80,22%","50,17%",...,"0,54%","0,12%","96,49%","0,67%","0,75%","1,82%","0,12%","1,77%","2,18%","0,88%"
2,2011,11,"Bogotá, D.C.",1479334,"90,7%","90,29%","68,63%","86,99%","84,7%","55,01%",...,0%,0%,"94,69%",0%,0%,"3,23%",0%,"2,3%","5,11%","2,57%"
3,2011,13,Bolívar,496676,"91,57%","91,4%","59,74%","90,81%","67,34%","39,17%",...,"2,1%","0,46%","95,48%","2,75%","3,67%","4,43%","0,46%","4,44%","5,37%","2,28%"
4,2011,15,Boyacá,300501,"86,16%","86,11%","63,36%","82,5%","74,65%","49,09%",...,"2,73%","0,17%","96,1%","4,31%","3,26%","2,62%","0,17%","1,9%","4,19%","1,55%"

In [21]:
print("--- Información General y Tipos de Datos ---")
data.info()

--- Información General y Tipos de Datos ---
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 462 entries, 0 to 461
Data columns (total 37 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   AÑO                          462 non-null    int64
 1   CÓDIGO_DEPARTAMENTO          462 non-null    int64
 2   DEPARTAMENTO                 462 non-null    object
 3   POBLACIÓN_5_16               462 non-null    int64
 4   TASA_MATRICULACIÓN_5_16      462 non-null    object
 5   COBERTURA_NETA               462 non-null    object
 6   COBERTURA_NETA_TRANSICIÓN    462 non-null    object
 7   COBERTURA_NETA_PRIMARIA      462 non-null    object
 8   COBERTURA_NETA_SECUNDARIA    462 non-null    object
 9   COBERTURA_NETA_MEDIA         462 non-null    object
 10  COBERTURA_BRUTA              462 non-null    object
 11  COBERTURA_BRUTA_TRANSICIÓN   462 non-null    object
 12  COBERTURA_BRUTA_PRIMARIA     462 non-null    object
 13  COBERTURA_BRUTA_SECUNDARIA   462 non-null    object
 14  COBERTURA_BRUTA_MEDIA        462 non-null    object
 15  TAMAÑO_PROMEDIO_DE_GRUPO     231 non-null    object
 16  SEDES_CONECTADAS_A_INTERNET  231 non-null    float64
 17  DESERCIÓN                    462 non-null    object
 18  DESERCIÓN_TRANSICIÓN         461 non-null    object
 19  DESERCIÓN_PRIMARIA           462 non-null    object
 20  DESERCIÓN_SECUNDARIA         462 non-null    object
 21  DESERCIÓN_MEDIA              462 non-null    object
 22  APROBACIÓN                   462 non-null    object
 23  APROBACIÓN_TRANSICIÓN        462 non-null    object
 24  APROBACIÓN_PRIMARIA          462 non-null    object
 25  APROBACIÓN_SECUNDARIA        462 non-null    object
 26  APROBACIÓN_MEDIA             462 non-null    object
 27  REPROBACIÓN                  462 non-null    object
 28  REPROBACIÓN_TRANSICIÓN       462 non-null    object
 29  REPROBACIÓN_PRIMARIA         462 non-null    object
 30  REPROBACIÓN_SECUNDARIA       462 non-null    object
 31  REPROBACIÓN_MEDIA            462 non-null    object
 32  REPITENCIA                   462 non-null    object
 33  REPITENCIA_TRANSICIÓN        462 non-null    object
 34  REPITENCIA_PRIMARIA          462 non-null    object
 35  REPITENCIA_SECUNDARIA        462 non-null    object
 36  REPITENCIA_MEDIA             462 non-null    object
dtypes: float64(1), int64(3), object(33)
memory usage: 133.7+ KB

In [22]:
print("\n--- Conteo de Valores Únicos ---")
print(data.nunique())

--- Conteo de Valores Únicos ---
AÑO                             14
CÓDIGO_DEPARTAMENTO             33
DEPARTAMENTO                    34
POBLACIÓN_5_16                 461
TASA_MATRICULACIÓN_5_16        421
COBERTURA_NETA                 428
COBERTURA_NETA_TRANSICIÓN      439
COBERTURA_NETA_PRIMARIA        426
COBERTURA_NETA_SECUNDARIA      441
COBERTURA_NETA_MEDIA           436
COBERTURA_BRUTA                425
COBERTURA_BRUTA_TRANSICIÓN     453
COBERTURA_BRUTA_PRIMARIA       440
COBERTURA_BRUTA_SECUNDARIA     437
COBERTURA_BRUTA_MEDIA          446
TAMAÑO_PROMEDIO_DE_GRUPO       225
SEDES_CONECTADAS_A_INTERNET    223
DESERCIÓN                      326
DESERCIÓN_TRANSICIÓN           331
DESERCIÓN_PRIMARIA             294
DESERCIÓN_SECUNDARIA           349
DESERCIÓN_MEDIA                301
APROBACIÓN                     369
APROBACIÓN_TRANSICIÓN          172
APROBACIÓN_PRIMARIA            370
APROBACIÓN_SECUNDARIA          349
APROBACIÓN_MEDIA               369
REPROBACIÓN                    368
REPROBACIÓN_TRANSICIÓN         226
REPROBACIÓN_PRIMARIA           370
REPROBACIÓN_SECUNDARIA         389
REPROBACIÓN_MEDIA              368
REPITENCIA                     355
REPITENCIA_TRANSICIÓN          226
REPITENCIA_PRIMARIA            340
REPITENCIA_SECUNDARIA          379
REPITENCIA_MEDIA               301
dtype: int64

In [23]:
print("\n--- Cantidad de Filas Duplicadas ---")
total_duplicados = data.duplicated().sum()
print(f"Total de filas exactas duplicadas: {total_duplicados}")

--- Cantidad de Filas Duplicadas ---
Total de filas exactas duplicadas: 0

In [24]:
print("\n--- Muestra de Valores Únicos por Columna ---")
for col in data.columns:
    valores_unicos = data[col].dropna().unique()
    print(f"[{col}] - Tipo: {data[col].dtype}")
    print(f"Muestra de únicos: {valores_unicos[:5]}\n")

--- Muestra de Valores Únicos por Columna ---
[AÑO] - Tipo: int64
Muestra de únicos: [2011 2012 2013 2014 2015]

[CÓDIGO_DEPARTAMENTO] - Tipo: int64
Muestra de únicos: [ 5  8 11 13 15]

[DEPARTAMENTO] - Tipo: object
Muestra de únicos: ['Antioquia' 'Atlántico' 'Bogotá, D.C.' 'Bolívar' 'Boyacá']

[POBLACIÓN_5_16] - Tipo: int64
Muestra de únicos: [1288473  523935 1479334  496676  300501]

[TASA_MATRICULACIÓN_5_16] - Tipo: object
Muestra de únicos: ['94,01%' '99,32%' '90,7%' '91,57%' '86,16%']

[COBERTURA_NETA] - Tipo: object
Muestra de únicos: ['93,85%' '99,05%' '90,29%' '91,4%' '86,11%']

[COBERTURA_NETA_TRANSICIÓN] - Tipo: object
Muestra de únicos: ['70,28%' '50,59%' '68,63%' '59,74%' '63,36%']

[COBERTURA_NETA_PRIMARIA] - Tipo: object
Muestra de únicos: ['94,12%' '98,93%' '86,99%' '90,81%' '82,5%']

[COBERTURA_NETA_SECUNDARIA] - Tipo: object
Muestra de únicos: ['75,68%' '80,22%' '84,7%' '67,34%' '74,65%']

[COBERTURA_NETA_MEDIA] - Tipo: object
Muestra de únicos: ['44,37%' '50,17%' '55,01%' '39,17%' '49,09%']

[COBERTURA_BRUTA] - Tipo: object
Muestra de únicos: ['106,81%' '107,88%' '97,78%' '110,41%' '104,15%']

[COBERTURA_BRUTA_TRANSICIÓN] - Tipo: object
Muestra de únicos: ['85,69%' '84,19%' '82,04%' '98,82%' '78,87%']

[COBERTURA_BRUTA_PRIMARIA] - Tipo: object
Muestra de únicos: ['117,5%' '120,41%' '97,94%' '126,45%' '99,88%']

[COBERTURA_BRUTA_SECUNDARIA] - Tipo: object
Muestra de únicos: ['110,81%' '107,89%' '106,48%' '108,15%' '119,78%']

[COBERTURA_BRUTA_MEDIA] - Tipo: object
Muestra de únicos: ['84,06%' '87,98%' '87,76%' '80,64%' '94,76%']

[TAMAÑO_PROMEDIO_DE_GRUPO] - Tipo: object
Muestra de únicos: ['27,47' '24,42' '26,75' '20,8' '22,77']

[SEDES_CONECTADAS_A_INTERNET] - Tipo: float64
Muestra de únicos: [74.48 80.46 94.21 30.12 25.26]

[DESERCIÓN] - Tipo: object
Muestra de únicos: ['3,97%' '2,76%' '3,95%' '3,14%' '3,07%']

[DESERCIÓN_TRANSICIÓN] - Tipo: object
Muestra de únicos: ['3,62%' '2,6%' '10,05%' '1,85%' '2,4%']

[DESERCIÓN_PRIMARIA] - Tipo: object
Muestra de únicos: ['3,65%' '3,06%' '5,3%' '2,93%' '2,24%']

[DESERCIÓN_SECUNDARIA] - Tipo: object
Muestra de únicos: ['4,57%' '2,42%' '1,96%' '3,79%' '4,03%']

[DESERCIÓN_MEDIA] - Tipo: object
Muestra de únicos: ['3,71%' '2,61%' '2,55%' '3,13%' '3,51%']

[APROBACIÓN] - Tipo: object
Muestra de únicos: ['93,98%' '96,7%' '96,05%' '94,76%' '94,2%']

[APROBACIÓN_TRANSICIÓN] - Tipo: object
Muestra de únicos: ['0,07%' '0,12%' '0%' '0,46%' '0,17%']

[APROBACIÓN_PRIMARIA] - Tipo: object
Muestra de únicos: ['94,56%' '96,49%' '94,69%' '95,48%' '96,1%']

[APROBACIÓN_SECUNDARIA] - Tipo: object
Muestra de únicos: ['4,57%' '2,42%' '1,96%' '3,79%' '4,03%']

[APROBACIÓN_MEDIA] - Tipo: object
Muestra de únicos: ['93,33%' '96,64%' '97,45%' '93,2%' '93,23%']

[REPROBACIÓN] - Tipo: object
Muestra de únicos: ['2,06%' '0,54%' '0%' '2,1%' '2,73%']

[REPROBACIÓN_TRANSICIÓN] - Tipo: object
Muestra de únicos: ['0,07%' '0,12%' '0%' '0,46%' '0,17%']

[REPROBACIÓN_PRIMARIA] - Tipo: object
Muestra de únicos: ['94,56%' '96,49%' '94,69%' '95,48%' '96,1%']

[REPROBACIÓN_SECUNDARIA] - Tipo: object
Muestra de únicos: ['2,54%' '0,67%' '0%' '2,75%' '4,31%']

[REPROBACIÓN_MEDIA] - Tipo: object
Muestra de únicos: ['2,96%' '0,75%' '0%' '3,67%' '3,26%']

[REPITENCIA] - Tipo: object
Muestra de únicos: ['4,25%' '1,82%' '3,23%' '4,43%' '2,62%']

[REPITENCIA_TRANSICIÓN] - Tipo: object
Muestra de únicos: ['0,07%' '0,12%' '0%' '0,46%' '0,17%']

[REPITENCIA_PRIMARIA] - Tipo: object
Muestra de únicos: ['4,56%' '1,77%' '2,3%' '4,44%' '1,9%']

[REPITENCIA_SECUNDARIA] - Tipo: object
Muestra de únicos: ['5,27%' '2,18%' '5,11%' '5,37%' '4,19%']

[REPITENCIA_MEDIA] - Tipo: object
Muestra de únicos: ['1,68%' '0,88%' '2,57%' '2,28%' '1,55%']

In [25]:
cols_porcentajes = [
    'TASA_MATRICULACIÓN_5_16', 'COBERTURA_NETA', 'COBERTURA_NETA_TRANSICIÓN',
    'COBERTURA_NETA_PRIMARIA', 'COBERTURA_NETA_SECUNDARIA', 'COBERTURA_NETA_MEDIA',
    'COBERTURA_BRUTA', 'COBERTURA_BRUTA_TRANSICIÓN', 'COBERTURA_BRUTA_PRIMARIA',
    'COBERTURA_BRUTA_SECUNDARIA', 'COBERTURA_BRUTA_MEDIA', 'DESERCIÓN',
    'DESERCIÓN_TRANSICIÓN', 'DESERCIÓN_PRIMARIA', 'DESERCIÓN_SECUNDARIA',
    'DESERCIÓN_MEDIA', 'APROBACIÓN', 'APROBACIÓN_TRANSICIÓN', 'APROBACIÓN_PRIMARIA',
    'APROBACIÓN_SECUNDARIA', 'APROBACIÓN_MEDIA', 'REPROBACIÓN', 'REPROBACIÓN_TRANSICIÓN',
    'REPROBACIÓN_PRIMARIA', 'REPROBACIÓN_SECUNDARIA', 'REPROBACIÓN_MEDIA', 'REPITENCIA',
    'REPITENCIA_TRANSICIÓN', 'REPITENCIA_PRIMARIA', 'REPITENCIA_SECUNDARIA', 'REPITENCIA_MEDIA'
]

for col in cols_porcentajes:
    data[col] = data[col].astype(str).str.replace('%', '', regex=False).str.replace(',', '.', regex=False)
    data[col] = pd.to_numeric(data[col], errors='coerce') / 100

data['TAMAÑO_PROMEDIO_DE_GRUPO'] = data['TAMAÑO_PROMEDIO_DE_GRUPO'].astype(str).str.replace(',', '.', regex=False)
data['TAMAÑO_PROMEDIO_DE_GRUPO'] = pd.to_numeric(data['TAMAÑO_PROMEDIO_DE_GRUPO'], errors='coerce')

data['SEDES_CONECTADAS_A_INTERNET'] = data['SEDES_CONECTADAS_A_INTERNET'] / 100

print(data.dtypes)

AÑO                              int64
CÓDIGO_DEPARTAMENTO              int64
DEPARTAMENTO                    object
POBLACIÓN_5_16                   int64
TASA_MATRICULACIÓN_5_16        float64
COBERTURA_NETA                 float64
COBERTURA_NETA_TRANSICIÓN      float64
COBERTURA_NETA_PRIMARIA        float64
COBERTURA_NETA_SECUNDARIA      float64
COBERTURA_NETA_MEDIA           float64
COBERTURA_BRUTA                float64
COBERTURA_BRUTA_TRANSICIÓN     float64
COBERTURA_BRUTA_PRIMARIA       float64
COBERTURA_BRUTA_SECUNDARIA     float64
COBERTURA_BRUTA_MEDIA          float64
TAMAÑO_PROMEDIO_DE_GRUPO       float64
SEDES_CONECTADAS_A_INTERNET    float64
DESERCIÓN                      float64
DESERCIÓN_TRANSICIÓN           float64
DESERCIÓN_PRIMARIA             float64
DESERCIÓN_SECUNDARIA           float64
DESERCIÓN_MEDIA                float64
APROBACIÓN                     float64
APROBACIÓN_TRANSICIÓN          float64
APROBACIÓN_PRIMARIA            float64
APROBACIÓN_SECUNDARIA          float64
APROBACIÓN_MEDIA               float64
REPROBACIÓN                    float64
REPROBACIÓN_TRANSICIÓN         float64
REPROBACIÓN_PRIMARIA           float64
REPROBACIÓN_SECUNDARIA         float64
REPROBACIÓN_MEDIA              float64
REPITENCIA                     float64
REPITENCIA_TRANSICIÓN          float64
REPITENCIA_PRIMARIA            float64
REPITENCIA_SECUNDARIA          float64
REPITENCIA_MEDIA               float64
dtype: object

In [26]:
data.head()

,AÑO,CÓDIGO_DEPARTAMENTO,DEPARTAMENTO,POBLACIÓN_5_16,TASA_MATRICULACIÓN_5_16,COBERTURA_NETA,COBERTURA_NETA_TRANSICIÓN,COBERTURA_NETA_PRIMARIA,COBERTURA_NETA_SECUNDARIA,COBERTURA_NETA_MEDIA,...,REPROBACIÓN,REPROBACIÓN_TRANSICIÓN,REPROBACIÓN_PRIMARIA,REPROBACIÓN_SECUNDARIA,REPROBACIÓN_MEDIA,REPITENCIA,REPITENCIA_TRANSICIÓN,REPITENCIA_PRIMARIA,REPITENCIA_SECUNDARIA,REPITENCIA_MEDIA
0,2011,5,Antioquia,1288473,0.9401,0.9385,0.7028,0.9412,0.7568,0.4437,...,0.0206,0.0007,0.9456,0.0254,0.0296,0.0425,0.0007,0.0456,0.0527,0.0168
1,2011,8,Atlántico,523935,0.9932,0.9905,0.5059,0.9893,0.8022,0.5017,...,0.0054,0.0012,0.9649,0.0067,0.0075,0.0182,0.0012,0.0177,0.0218,0.0088
2,2011,11,"Bogotá, D.C.",1479334,0.9070,0.9029,0.6863,0.8699,0.8470,0.5501,...,0.0000,0.0000,0.9469,0.0000,0.0000,0.0323,0.0000,0.0230,0.0511,0.0257
3,2011,13,Bolívar,496676,0.9157,0.9140,0.5974,0.9081,0.6734,0.3917,...,0.0210,0.0046,0.9548,0.0275,0.0367,0.0443,0.0046,0.0444,0.0537,0.0228
4,2011,15,Boyacá,300501,0.8616,0.8611,0.6336,0.8250,0.7465,0.4909,...,0.0273,0.0017,0.9610,0.0431,0.0326,0.0262,0.0017,0.0190,0.0419,0.0155

In [27]:
data.to_csv('datos_educacion_limpios.csv',
            index=False,
            encoding='utf-8-sig',
            sep=';',
            decimal=',')

In [ ]:
data.to_json(
    'data.json',
    orient='records',
    force_ascii=False,
    indent=4
)